---
  - name: clickhouse-role
    src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
  - name: vector-role
    src: git@github.com:kirill-karagodin/vector-role.git
    scm: git
    version: "1.3.2"
  - name: nginx-role
    src: git@github.com:kirill-karagodin/nginx-role.git
    scm: git
    version: "1.0.2"
  - name: lighthouse-role
    src: git@github.com:kirill-karagodin/lighthouse-role.git
    scm: git
    version: "1.0.2"
