---
# Установка Clickhouse
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse-role

# Установка Vector
- name: Install Vector
  hosts: vector
  roles:
    - vector-role

# Установка Nginx для Lighthouse
- name: Install Nginx
  hosts: lighthouse
  roles:
    - nginx-role

# Установка Lighthouse
- name: Install Lighthouse
  hosts: lighthouse
  roles:
     - lighthouse-role
# Вывод URL
  post_tasks:
    - name: Show connect URL lighthouse
      debug:
        msg: "http://{{ ansible_host }}/#http://{{ hostvars['clickhouse-01'].ansible_host }}:8123/?user={{ clickhouse_user }}"
